--오라클 주석
/*
여러줄 주석
오라클은 대소문자 구분하지 않습니다.
*/
SELECT * FROM EMPLOYEES;
SELECT FIRST_NAME, EMAIL, HIRE_DATE FROM EMPLOYEES;
SELECT JOB_ID, SALARY, DEPARTMENT_ID FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

--연산
--컬럼을 조회하는 위치에서 * / + -

SELECT FIRST_NAME, SALARY , SALARY + SALARY * 0.1 FROM EMPLOYEES;

--NULL
SELECT FIRST_NAME,COMMISSION_PCT FROM EMPLOYEES;

--엘리어스 as - AS 별칭, 별칭, "별칭" 가능
SELECT FIRST_NAME AS 이름, 
    LAST_NAME AS 성, 
    SALARY "급여",
    SALARY + SALARY * 0.1 총급여 
FROM EMPLOYEES;

--오라클에서는 || OR연산자로 문자열을 더할 수 있습니다.
--오라클은 문자열을 ''로 표현합니다. 문자열안에서 '를 사용하고 싶으면 두번쓰면 됩니다. ''
SELECT FIRST_NAME || ' ' || LAST_NAME || 'IS SALARY $' || SALARY AS 급여내역 FROM EMPLOYEES;

--DISTINCT 중복제거
SELECT DISTINCT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

--ROWID(데이터의 주소), ROWNUM(조회된 순서)
SELECT ROWNUM, ROWID, EMPLOYEE_ID, FIRST_NAME FROM EMPLOYEES;